services:
  - type: web
    name: n8n-selfhosted
    env: node
    buildCommand: |
      corepack enable
      corepack prepare yarn@3.6.4 --activate
      yarn install
      yarn build
    startCommand: yarn start
    envVars:
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-selfhosted-h1pq.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Seoul
