services:
  - type: web
    name: n8n-selfhosted
    env: node
    plan: free
    buildCommand: |
      corepack enable
      corepack prepare yarn@3.1.1 --activate
      yarn install
      yarn build
    startCommand: yarn start
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "10000"
      - key: WEBHOOK_URL
        value: "https://n8n-selfhosted-h1pq.onrender.com"
